<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->json('pokemons')->default(json_encode([
                "bulbasaur"=> false,
                "ivysaur"=> false,
                "venusaur"=> false,
                "charmander"=> false,
                "charmeleon"=> false,
                "charizard"=> false,
                "squirtle"=> false,
                "wartortle"=> false,
                "blastoise"=> false,
                "caterpie"=> false,
                "metapod"=> false,
                "butterfree"=> false,
                "weedle"=> false,
                "kakuna"=> false,
                "beedrill"=> false,
                "pidgey"=> false,
                "pidgeotto"=> false,
                "pidgeot"=> false,
                "rattata"=> false,
                "raticate"=> false,
                "spearow"=> false,
                "fearow"=> false,
                "ekans"=> false,
                "arbok"=> false,
                "pikachu"=> false,
                "raichu"=> false,
                "sandshrew"=> false,
                "sandslash"=> false,
                "nidoran-f"=> false,
                "nidorina"=> false,
                "nidoqueen"=> false,
                "nidoran-m"=> false,
                "nidorino"=> false,
                "nidoking"=> false,
                "clefairy"=> false,
                "clefable"=> false,
                "vulpix"=> false,
                "ninetales"=> false,
                "jigglypuff"=> false,
                "wigglytuff"=> false,
                "zubat"=> false,
                "golbat"=> false,
                "oddish"=> false,
                "gloom"=> false,
                "vileplume"=> false,
                "paras"=> false,
                "parasect"=> false,
                "venonat"=> false,
                "venomoth"=> false,
                "diglett"=> false,
                "dugtrio"=> false,
                "meowth"=> false,
                "persian"=> false,
                "psyduck"=> false,
                "golduck"=> false,
                "mankey"=> false,
                "primeape"=> false,
                "growlithe"=> false,
                "arcanine"=> false,
                "poliwag"=> false,
                "poliwhirl"=> false,
                "poliwrath"=> false,
                "abra"=> false,
                "kadabra"=> false,
                "alakazam"=> false,
                "machop"=> false,
                "machoke"=> false,
                "machamp"=> false,
                "bellsprout"=> false,
                "weepinbell"=> false,
                "victreebel"=> false,
                "tentacool"=> false,
                "tentacruel"=> false,
                "geodude"=> false,
                "graveler"=> false,
                "golem"=> false,
                "ponyta"=> false,
                "rapidash"=> false,
                "slowpoke"=> false,
                "slowbro"=> false,
                "magnemite"=> false,
                "magneton"=> false,
                "farfetchd"=> false,
                "doduo"=> false,
                "dodrio"=> false,
                "seel"=> false,
                "dewgong"=> false,
                "grimer"=> false,
                "muk"=> false,
                "shellder"=> false,
                "cloyster"=> false,
                "gastly"=> false,
                "haunter"=> false,
                "gengar"=> false,
                "onix"=> false,
                "drowzee"=> false,
                "hypno"=> false,
                "krabby"=> false,
                "kingler"=> false,
                "voltorb"=> false,
                "electrode"=> false,
                "exeggcute"=> false,
                "exeggutor"=> false,
                "cubone"=> false,
                "marowak"=> false,
                "hitmonlee"=> false,
                "hitmonchan"=> false,
                "lickitung"=> false,
                "koffing"=> false,
                "weezing"=> false,
                "rhyhorn"=> false,
                "rhydon"=> false,
                "chansey"=> false,
                "tangela"=> false,
                "kangaskhan"=> false,
                "horsea"=> false,
                "seadra"=> false,
                "goldeen"=> false,
                "seaking"=> false,
                "staryu"=> false,
                "starmie"=> false,
                "mr-mime"=> false,
                "scyther"=> false,
                "jynx"=> false,
                "electabuzz"=> false,
                "magmar"=> false,
                "pinsir"=> false,
                "tauros"=> false,
                "magikarp"=> false,
                "gyarados"=> false,
                "lapras"=> false,
                "ditto"=> false,
                "eevee"=> false,
                "vaporeon"=> false,
                "jolteon"=> false,
                "flareon"=> false,
                "porygon"=> false,
                "omanyte"=> false,
                "omastar"=> false,
                "kabuto"=> false,
                "kabutops"=> false,
                "aerodactyl"=> false,
                "snorlax"=> false,
                "articuno"=> false,
                "zapdos"=> false,
                "moltres"=> false,
                "dratini"=> false,
                "dragonair"=> false,
                "dragonite"=> false,
                "mewtwo"=> false,
                "mew"=> false
            ]));
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('pokemons');
        });
    }
};